import subprocess
import tempfile
import unittest
from pathlib import Path

from scripts.check_release_metadata import LOCK_FILES, check_release_metadata


class ReleaseMetadataGateTests(unittest.TestCase):
    def run_git(self, root: Path, *args: str) -> None:
        subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )

    def make_repo(
        self,
        root: Path,
        *,
        readme_version: str = "0.1.7",
        source_version: str = "0.1.7",
        stable_version: str = "0.1.7",
        source_notes_status: str = "unreleased",
        tag_kind: str | None = "annotated",
    ) -> None:
        version_dir = root / "scripts" / "invoice_fetch"
        notes_dir = root / "docs" / "release-notes"
        version_dir.mkdir(parents=True)
        notes_dir.mkdir(parents=True)
        (version_dir / "version.py").write_text(
            f'VERSION = "{source_version}"\n'
            f'STABLE_VERSION = "{stable_version}"\n',
            encoding="utf-8",
        )
        readme = (
            f"[Invoice Hub v{readme_version}]"
            f"(https://github.com/if16888/invoice-hub/releases/tag/v{readme_version})\n"
            f"v{readme_version} Stable\n"
        )
        if source_version != stable_version:
            readme += f"v{source_version} 当前仍为未发布开发线\n"
        (root / "README.md").write_text(readme, encoding="utf-8")
        (notes_dir / f"v{stable_version}.md").write_text(
            "> Status: **Stable — published on 2026-08-25.**\n",
            encoding="utf-8",
        )
        if source_version != stable_version:
            source_status = (
                "> Status: **Stable — published on 2026-09-02.**\n"
                if source_notes_status == "stable"
                else "> Status: **Unreleased — previous candidate superseded.**\n"
            )
            (notes_dir / f"v{source_version}.md").write_text(
                source_status,
                encoding="utf-8",
            )
        for relative in LOCK_FILES:
            (root / relative).write_text(
                "#\n# This file is autogenerated by pip-compile with Python 3.11\n",
                encoding="utf-8",
            )
        self.run_git(root, "init", "--quiet")
        self.run_git(root, "config", "user.email", "release-gate-tests@example.invalid")
        self.run_git(root, "config", "user.name", "Release Gate Tests")
        self.run_git(root, "add", ".")
        self.run_git(root, "commit", "--quiet", "-m", "fixture")
        if tag_kind == "annotated":
            self.run_git(
                root,
                "tag",
                "-a",
                f"v{stable_version}",
                "-m",
                "stable fixture",
            )
        elif tag_kind == "lightweight":
            self.run_git(root, "tag", f"v{stable_version}")

    def test_consistent_release_metadata_passes(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root)
            self.assertEqual(check_release_metadata(root), [])

    def test_readme_stable_version_mismatch_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, readme_version="0.1.6")
            errors = check_release_metadata(root)
            self.assertTrue(any("README" in error for error in errors), errors)

    def test_stable_metadata_with_annotated_tag_passes(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root)
            self.assertEqual(check_release_metadata(root), [])

    def test_stable_claim_without_tag_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, tag_kind=None)
            errors = check_release_metadata(root)
            self.assertTrue(any("annotated tag" in error for error in errors), errors)

    def test_lightweight_tag_is_insufficient(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, tag_kind="lightweight")
            errors = check_release_metadata(root)
            self.assertTrue(any("annotated tag" in error for error in errors), errors)

    def test_source_newer_than_stable_passes(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, source_version="0.1.8")
            self.assertEqual(check_release_metadata(root), [])

    def test_unreleased_source_falsely_claiming_stable_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(
                root,
                source_version="0.1.8",
                source_notes_status="stable",
            )
            errors = check_release_metadata(root)
            self.assertTrue(any("0.1.8" in error for error in errors), errors)

    def test_lock_header_python_version_mismatch_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root)
            (root / "requirements-desktop.lock.txt").write_text(
                "#\n# This file is autogenerated by pip-compile with Python 3.14\n",
                encoding="utf-8",
            )
            errors = check_release_metadata(root)
            self.assertIn(
                "requirements-desktop.lock.txt header 必须声明 Python 3.11",
                errors,
            )


if __name__ == "__main__":
    unittest.main()
