import subprocess
import tempfile
import unittest
from pathlib import Path

from scripts.check_release_metadata import (
    LIVE_PUBLICATION_AUTHORITY,
    LOCK_FILES,
    check_release_metadata,
)


class ReleaseMetadataGateTests(unittest.TestCase):
    def run_git(self, root: Path, *args: str) -> None:
        subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )

    def make_repo(
        self,
        root: Path,
        *,
        source_version: str = "0.1.8",
        previous_stable_version: str = "0.1.7",
        readme_previous_version: str | None = None,
        readme_source_state: str = "neutral",
        source_notes_state: str = "neutral",
        previous_tag_kind: str | None = "annotated",
        source_tag_kind: str | None = None,
    ) -> None:
        readme_previous_version = readme_previous_version or previous_stable_version
        version_dir = root / "scripts" / "invoice_fetch"
        notes_dir = root / "docs" / "release-notes"
        version_dir.mkdir(parents=True)
        notes_dir.mkdir(parents=True)

        (version_dir / "version.py").write_text(
            f'VERSION = "{source_version}"\n'
            f'PREVIOUS_STABLE_VERSION = "{previous_stable_version}"\n',
            encoding="utf-8",
        )

        readme = (
            f"[v{source_version} release notes]"
            f"(docs/release-notes/v{source_version}.md)\n"
            f"[Invoice Hub v{readme_previous_version}]"
            f"(https://github.com/if16888/invoice-hub/releases/tag/"
            f"v{readme_previous_version})\n"
            "Live publication status: GitHub Releases\n"
        )
        if readme_source_state == "unreleased":
            readme += f"v{source_version} 当前仍为未发布开发线\n"
        elif readme_source_state == "stable":
            readme += f"v{source_version} Stable\n"
        (root / "README.md").write_text(readme, encoding="utf-8")

        (notes_dir / f"v{previous_stable_version}.md").write_text(
            "> Status: **Stable — published on 2026-08-25.**\n",
            encoding="utf-8",
        )
        if source_notes_state == "stable":
            source_notes = "> Status: **Stable — published on 2026-09-06.**\n"
        elif source_notes_state == "unreleased":
            source_notes = "> Status: **Unreleased.**\n"
        else:
            source_notes = (
                f"> Release line: **v{source_version}.** "
                f"{LIVE_PUBLICATION_AUTHORITY}\n"
            )
        (notes_dir / f"v{source_version}.md").write_text(
            source_notes,
            encoding="utf-8",
        )

        for relative in LOCK_FILES:
            (root / relative).write_text(
                "#\n# This file is autogenerated by pip-compile with Python 3.11\n",
                encoding="utf-8",
            )

        self.run_git(root, "init", "--quiet")
        self.run_git(root, "config", "user.email", "release-gate-tests@example.invalid")
        self.run_git(root, "config", "user.name", "Release Gate Tests")
        self.run_git(root, "add", ".")
        self.run_git(root, "commit", "--quiet", "-m", "fixture")
        self.create_tag(root, previous_stable_version, previous_tag_kind)
        self.create_tag(root, source_version, source_tag_kind)

    def create_tag(self, root: Path, version: str, kind: str | None) -> None:
        if kind == "annotated":
            self.run_git(root, "tag", "-a", f"v{version}", "-m", "fixture tag")
        elif kind == "lightweight":
            self.run_git(root, "tag", f"v{version}")

    def test_consistent_time_stable_release_metadata_passes(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root)
            self.assertEqual(check_release_metadata(root), [])

    def test_readme_previous_stable_version_mismatch_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, readme_previous_version="0.1.6")
            errors = check_release_metadata(root)
            self.assertTrue(any("README" in error for error in errors), errors)

    def test_previous_stable_requires_annotated_tag(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, previous_tag_kind=None)
            errors = check_release_metadata(root)
            self.assertTrue(any("historical stable" in error for error in errors), errors)

    def test_previous_stable_lightweight_tag_is_insufficient(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, previous_tag_kind="lightweight")
            errors = check_release_metadata(root)
            self.assertTrue(any("must be annotated" in error for error in errors), errors)

    def test_source_line_without_tag_passes_before_publication(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, source_tag_kind=None)
            self.assertEqual(check_release_metadata(root), [])

    def test_source_line_with_annotated_tag_passes_after_tagging(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, source_tag_kind="annotated")
            self.assertEqual(check_release_metadata(root), [])

    def test_source_line_lightweight_tag_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, source_tag_kind="lightweight")
            errors = check_release_metadata(root)
            self.assertTrue(any("v0.1.8 tag must be annotated" in error for error in errors), errors)

    def test_source_notes_must_not_hardcode_unreleased_state(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, source_notes_state="unreleased")
            errors = check_release_metadata(root)
            self.assertTrue(any("Unreleased" in error for error in errors), errors)

    def test_source_notes_must_not_hardcode_published_state(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, source_notes_state="stable")
            errors = check_release_metadata(root)
            self.assertTrue(any("Stable" in error for error in errors), errors)

    def test_readme_must_not_hardcode_source_unreleased_state(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, readme_source_state="unreleased")
            errors = check_release_metadata(root)
            self.assertTrue(any("GitHub Releases" in error for error in errors), errors)

    def test_readme_must_not_hardcode_source_published_state(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, readme_source_state="stable")
            errors = check_release_metadata(root)
            self.assertTrue(any("GitHub Releases" in error for error in errors), errors)

    def test_lock_header_python_version_mismatch_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root)
            (root / "requirements-desktop.lock.txt").write_text(
                "#\n# This file is autogenerated by pip-compile with Python 3.14\n",
                encoding="utf-8",
            )
            errors = check_release_metadata(root)
            self.assertIn(
                "requirements-desktop.lock.txt header 必须声明 Python 3.11",
                errors,
            )


if __name__ == "__main__":
    unittest.main()
