import tempfile
import unittest
from pathlib import Path

from scripts.check_release_metadata import LOCK_FILES, check_release_metadata


class ReleaseMetadataGateTests(unittest.TestCase):
    def make_repo(self, root: Path, *, readme_version: str = "0.1.7") -> None:
        version_dir = root / "scripts" / "invoice_fetch"
        notes_dir = root / "docs" / "release-notes"
        version_dir.mkdir(parents=True)
        notes_dir.mkdir(parents=True)
        (version_dir / "version.py").write_text(
            'VERSION = "0.1.7"\n',
            encoding="utf-8",
        )
        (root / "README.md").write_text(
            f"[Invoice Hub v{readme_version}]"
            f"(https://github.com/if16888/invoice-hub/releases/tag/v{readme_version})\n"
            f"v{readme_version} Stable\n",
            encoding="utf-8",
        )
        (notes_dir / "v0.1.7.md").write_text(
            "> Status: **Stable — published on 2026-08-25.**\n",
            encoding="utf-8",
        )
        for relative in LOCK_FILES:
            (root / relative).write_text(
                "#\n# This file is autogenerated by pip-compile with Python 3.11\n",
                encoding="utf-8",
            )

    def test_consistent_release_metadata_passes(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root)
            self.assertEqual(check_release_metadata(root), [])

    def test_readme_stable_version_mismatch_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root, readme_version="0.1.6")
            errors = check_release_metadata(root)
            self.assertTrue(any("README" in error for error in errors), errors)

    def test_lock_header_python_version_mismatch_fails(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            self.make_repo(root)
            (root / "requirements-desktop.lock.txt").write_text(
                "#\n# This file is autogenerated by pip-compile with Python 3.14\n",
                encoding="utf-8",
            )
            errors = check_release_metadata(root)
            self.assertIn(
                "requirements-desktop.lock.txt header 必须声明 Python 3.11",
                errors,
            )


if __name__ == "__main__":
    unittest.main()
