"""Generate PyInstaller Windows version metadata for Invoice Hub."""

from __future__ import annotations

import argparse
from pathlib import Path

from scripts.invoice_fetch.version import VERSION

_COMPANY_NAME = "Invoice Hub"
_PRODUCT_NAME = "Invoice Hub"
_FILE_DESCRIPTION = "Invoice Hub"
_INTERNAL_NAME = "InvoiceHub"
_ORIGINAL_FILENAME = "InvoiceHub.exe"
_TRANSLATION = "040904B0"


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = version.split(".")
    values: list[int] = []
    for part in parts[:4]:
        if not part.isdigit():
            raise ValueError(f"Version component must be numeric: {part!r}")
        values.append(int(part))
    while len(values) < 4:
        values.append(0)
    return tuple(values)  # type: ignore[return-value]


def build_version_info_text(version: str) -> str:
    filevers = _version_tuple(version)
    return f"""# UTF-8
#
# Generated by scripts.generate_windows_version_info
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={filevers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '{_TRANSLATION}',
        [
          StringStruct('CompanyName', '{_COMPANY_NAME}'),
          StringStruct('FileDescription', '{_FILE_DESCRIPTION}'),
          StringStruct('FileVersion', '{version}'),
          StringStruct('InternalName', '{_INTERNAL_NAME}'),
          StringStruct('OriginalFilename', '{_ORIGINAL_FILENAME}'),
          StringStruct('ProductName', '{_PRODUCT_NAME}'),
          StringStruct('ProductVersion', '{version}'),
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("build") / "windows-version-info.txt",
        help="Path to the generated PyInstaller version-info file.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    output = args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_version_info_text(VERSION), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
