"""Write the build identity consumed by frozen Invoice Hub packages."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from scripts.invoice_fetch.version import validate_build_version

_DEFAULT_OUTPUT = Path("scripts") / "invoice_fetch" / "_embedded_build_version.py"


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Validated build version.")
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help="Generated module path.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    version = validate_build_version(args.version)
    output = args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        '"""Generated by scripts.dev.write_embedded_build_version."""\\n\\n'
        f"BUILD_VERSION = {json.dumps(version)}\\n",
        encoding="utf-8",
    )
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
